version: "2"
run:
  concurrency: 4
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - gosec
    - ineffassign
    - intrange
    - mirror
    - mnd
    - musttag
    - nilerr
    - prealloc
    - predeclared
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
    tagliatelle:
      case:
        rules:
          json: goCamel
          yaml: goCamel
        use-field-name: true
    varnamelen:
      ignore-names:
        - db
        - w
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
