name: Release tagging

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Tag/Release on Push Action
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          tag_prefix: "v"
          bump_version_scheme: patch
