name: Release tagging

on:
  workflow_run:
    workflows: ["Lint, Test and Build"]
    types: [completed]
    branches: [master]
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-tagging
  cancel-in-progress: false

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Tag/Release on Push Action
        uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2 # v0.28.0
        with:
          tag_prefix: "v"
          bump_version_scheme: patch
